/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cun.edu.co.main.designer;
import cun.edu.co.main.User;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import cun.edu.co.main.Postgress_database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;

/**
 *
 * @author thor
 */
public class Showpanel extends javax.swing.JFrame {
    
    public DefaultTableModel dtm;
    public Object[] o = new Object[6];
    public java.util.ArrayList<User> listusers = new java.util.ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Showpanel.class.getName());

    /**
     * Creates new form Screen
     */
    public Showpanel() {
        initComponents();
        dtm = (DefaultTableModel) Table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        newcontact = new javax.swing.JButton();
        deletecontact = new javax.swing.JButton();
        savedata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        management = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewdata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setAutoCreateRowSorter(true);
        Table.setBackground(new java.awt.Color(0, 0, 0));
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Correo", "Cargo", "Gerencia", "Telefono", "Ubicación"
            }
        ));
        Table.setShowGrid(true);
        Table.setShowHorizontalLines(true);
        Table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(Table);

        newcontact.setBackground(new java.awt.Color(153, 0, 0));
        newcontact.setForeground(new java.awt.Color(0, 0, 0));
        newcontact.setText("New Register");
        newcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcontactActionPerformed(evt);
            }
        });

        deletecontact.setBackground(new java.awt.Color(153, 0, 0));
        deletecontact.setForeground(new java.awt.Color(0, 0, 0));
        deletecontact.setText("Delete Record");
        deletecontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecontactActionPerformed(evt);
            }
        });

        savedata.setBackground(new java.awt.Color(0, 204, 255));
        savedata.setForeground(new java.awt.Color(0, 0, 0));
        savedata.setText("Save Data");
        savedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel1.setText("Nombre y Apellido");

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        position.setBackground(new java.awt.Color(0, 0, 0));
        position.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        position.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel2.setText("Cargo");

        account.setBackground(new java.awt.Color(0, 0, 0));
        account.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));

        management.setBackground(new java.awt.Color(0, 0, 0));
        management.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        management.setForeground(new java.awt.Color(255, 255, 255));
        management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel3.setText("Correo Corporativo");

        jLabel5.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel5.setText("Gerencia");

        location.setBackground(new java.awt.Color(0, 0, 0));
        location.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel6.setText("Ubicación");

        phone.setBackground(new java.awt.Color(0, 0, 0));
        phone.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel7.setText("Telefono");

        viewdata.setBackground(new java.awt.Color(0, 204, 255));
        viewdata.setForeground(new java.awt.Color(0, 0, 0));
        viewdata.setText("View Data");
        viewdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phone)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletecontact, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savedata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewdata)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name)
                    .addComponent(account)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(management)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newcontact)
                    .addComponent(deletecontact)
                    .addComponent(savedata)
                    .addComponent(viewdata))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcontactActionPerformed
        //Llamo al texto de forma legible y con trim() elimino espacios en blanco  
        String namestr = name.getText().trim();
        String accountstr = account.getText().trim();
        String positionstr = position.getText().trim();
        String managementstr = management.getText().trim();
        String phonestr = phone.getText().trim();
        String locationstr = location.getText().trim();
        
        // Condicional que verifica que obligatoriamente se deben ingresar los datos minimos para realizar el registro
        if (namestr.isEmpty() || accountstr.isEmpty() || phonestr.isEmpty() ||locationstr.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, complete obligatotiamente Nombre, Correo, Telefono y Ubicación.",
                "Campos Incompletos",
                JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución del método aquí
    }
        
        //Hago uso del contructor en la clase User
        User users = new User(namestr,accountstr,positionstr,managementstr,phonestr,locationstr );
        
        //Crea un mensaje de confirmación de datos
        String message = "¿Son correctos los siguientes datos?\n\n" +
                                 "Nombre Completo: " + users.getName() + "\n" +
                                 "Correo Corporativo: " + users.getAccount() + "\n" +
                                 "Cargo: " + users.getPosition() + "\n" +
                                 "Gerencia " + users.getManagement() + "\n" +
                                 "Telefono: " + users.getPhone() +"\n" +
                                 "Ubicación: " + users.getLocation();
        
        //se crea con joptionpane una ventana de confirmación aparte
        int respuesta = JOptionPane.showConfirmDialog(this, // "this" es la ventana actual
            message,
            "Confirmar Registro",
            JOptionPane.YES_NO_OPTION, // Botones de "Sí" y "No"
            JOptionPane.INFORMATION_MESSAGE); // Icono de información
        
        
        //Condicional donde confirmamos que el usuario haya marcado Yes para poder continuar 
        if (respuesta == JOptionPane.YES_OPTION){
            //Agrego el objecto a la lista
            listusers.add(users);
        
             //Filas para la tabla, parte visual
             o[0] = users.getName();
             o[1] = users.getAccount();
             o[2] = users.getPosition();
             o[3] = users.getManagement();
             o[4] = users.getPhone();
             o[5] = users.getLocation();
        
            //Agrego las filas (o) a la tabla, parte visual
            dtm.addRow(o);
        
            //Una vez agregado los datos, estos se limpian, para agregar otros
            name.setText("");
            account.setText("");
            position.setText("");
            management.setText("");
            phone.setText("");
            location.setText("");
            
            //Mensaje final donde confirmamos que el usuario se registro correctamente
            JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
         
        }
             
    }//GEN-LAST:event_newcontactActionPerformed

    private void deletecontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecontactActionPerformed
       // El sistema dependiendo de donde se ponga el cursor detecta que columna o numero es
        int listselect = Table.getSelectedRow();

        // Solo continúa si listselect es 0 
        if (listselect >= 0) {
        
        // Usamos el índice de la tabla (listselect) para tomar el User de tu ArrayList
        User userParaBorrar = listusers.get(listselect);

        //Mensaje para confirmar la eliminacion del registro
        String message = "¿Está seguro de que desea eliminar este registro?\n\n" +
                         "Nombre Completo: " + userParaBorrar.getName() + "\n" +
                         "Correo Corporativo: " + userParaBorrar.getAccount() + "\n" +
                         "Cargo: " + userParaBorrar.getPosition() + "\n" +
                         "Gerencia: " + userParaBorrar.getManagement() + "\n" +
                         "Telefono: " + userParaBorrar.getPhone() + "\n" +
                         "Ubicación: " + userParaBorrar.getLocation();

           int respuesta = JOptionPane.showConfirmDialog(this,
            message,
            "Confirmar Eliminación", // Título más apropiado
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE); // Icono de advertencia es mejor para borrar

        // Solo si el usuario presiona "Sí"...
        if (respuesta == JOptionPane.YES_OPTION) {
            
            // ...procede a borrar de la lista y de la tabla.
            listusers.remove(listselect);
            dtm.removeRow(listselect);
            
           //Mensaje confirmando la eliminación del registro 
           JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente.");
        }
        
        } else {
        //Notifica al usuario si no se ha seleccionado un registro para poder eliminarlo
        JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione un registro de la tabla para eliminar.", 
                "Ningún registro seleccionado", 
                JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_deletecontactActionPerformed

    private void savedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedataActionPerformed
if (listusers.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay registros nuevos para guardar.");
        return;
    }

    String sql = "INSERT INTO users (name, account, position, management, phone, location) " +
                 "VALUES (?, ?, ?, ?, ?, ?)";
    
    Postgress_database database = new Postgress_database();

    // 1. Usamos try-with-resources para la conexión.
    // Esto asegura que la conexión SIEMPRE se cierre, sin un 'finally'.
    try (Connection conn = database.conectar()) {

        // 2. ¡AQUÍ ESTÁ LA PARTE MANUAL!
        // Apagamos el auto-guardado.
        conn.setAutoCommit(false);
        
        // 3. Preparamos la consulta
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            for (User user : listusers) {
                // 4. Llenamos los datos
                pstmt.setString(1, user.getName());
                pstmt.setString(2, user.getAccount());
                pstmt.setString(3, user.getPosition());
                pstmt.setString(4, user.getManagement());
                pstmt.setString(5, user.getPhone());
                pstmt.setString(6, user.getLocation());
                
                // 5. Ejecutamos, pero NO se guarda en la BD (solo se prepara)
                pstmt.executeUpdate();
            }
        } // El PreparedStatement se cierra aquí
        
        // 6. Si el bucle terminó sin errores, GUARDAMOS TODO DE GOLPE.
        conn.commit();

        // 7. Informar al usuario y limpiar
        JOptionPane.showMessageDialog(this,
                "¡Se guardaron " + listusers.size() + " registros exitosamente!",
                "Guardado Exitoso",
                JOptionPane.INFORMATION_MESSAGE);
        
        listusers.clear();
        dtm.setRowCount(0);

    } catch (SQLException e) {
        // 8. SI HAY UN ERROR, EL 'conn.commit()' NUNCA SE EJECUTÓ.
        // La base de datos descartará automáticamente los cambios.
        JOptionPane.showMessageDialog(this,
                "Error al guardar. No se guardó ningún registro.\n" + e.getMessage(),
                "Error SQL",
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    // 9. No necesitamos 'finally' ni 'conn.close()'. El 'try-with-resources' lo hace solo.

     
    }//GEN-LAST:event_savedataActionPerformed

    private void managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managementActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void viewdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdataActionPerformed
        // limpiar tabla para no mostrar duplicados
        dtm.setRowCount(0);
        
        //Usamos la consulta para mostrar la información de la base de datos
        String sql = "SELECT * FROM users ORDER BY name ASC";
        
        //creamos la instalacia de la base de datos
        Postgress_database database = new Postgress_database();
        
try (Connection conn = database.conectar();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            
            // 2. Creamos la fila
            Object[] fila = new Object[6];
            
            // 3. Llenamos la fila pidiendo la columna POR SU NOMBRE
            // Esto es más seguro que usar números
            fila[0] = rs.getString("name");
            fila[1] = rs.getString("account");
            fila[2] = rs.getString("position");
            fila[3] = rs.getString("management");
            fila[4] = rs.getString("phone");
            fila[5] = rs.getString("location");

            // 4. Añadimos la fila a la tabla visual
            dtm.addRow(fila);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        e.printStackTrace();
    }

             
    }//GEN-LAST:event_viewdataActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField account;
    private javax.swing.JButton deletecontact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField management;
    private javax.swing.JTextField name;
    private javax.swing.JButton newcontact;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField position;
    private javax.swing.JButton savedata;
    private javax.swing.JButton viewdata;
    // End of variables declaration//GEN-END:variables
}
