/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cun.edu.co.main.designer;
import cun.edu.co.main.User;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import cun.edu.co.main.Postgress_database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author thor
 */
public class Showpanel extends javax.swing.JFrame {
    
    public DefaultTableModel dtm;
    public Object[] o = new Object[6];
    public java.util.ArrayList<User> listusers = new java.util.ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Showpanel.class.getName());

    /**
     * Creates new form Screen
     */
    public Showpanel() {
        initComponents();
        dtm = (DefaultTableModel) Table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        newcontact = new javax.swing.JButton();
        deletecontact = new javax.swing.JButton();
        savedata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        management = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setAutoCreateRowSorter(true);
        Table.setBackground(new java.awt.Color(102, 102, 102));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Correo", "Cargo", "Gerencia", "Telefono", "Ubicación"
            }
        ));
        Table.setShowGrid(false);
        Table.setShowHorizontalLines(true);
        Table.setShowVerticalLines(true);
        jScrollPane1.setViewportView(Table);

        newcontact.setBackground(new java.awt.Color(102, 102, 102));
        newcontact.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        newcontact.setText("Ingresar Registro");
        newcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcontactActionPerformed(evt);
            }
        });

        deletecontact.setBackground(new java.awt.Color(102, 102, 102));
        deletecontact.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        deletecontact.setText("Delete Record");
        deletecontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecontactActionPerformed(evt);
            }
        });

        savedata.setBackground(new java.awt.Color(102, 102, 102));
        savedata.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        savedata.setText("Guardar Data en SQL");
        savedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel1.setText("Nombre Completo");

        name.setBackground(new java.awt.Color(102, 102, 102));
        name.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N

        position.setBackground(new java.awt.Color(102, 102, 102));
        position.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel2.setText("Cargo");

        account.setBackground(new java.awt.Color(102, 102, 102));
        account.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N

        management.setBackground(new java.awt.Color(102, 102, 102));
        management.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel3.setText("Correo Corporativo");

        jLabel5.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel5.setText("Gerencia");

        location.setBackground(new java.awt.Color(102, 102, 102));
        location.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel6.setText("Ubicación");

        phone.setBackground(new java.awt.Color(102, 102, 102));
        phone.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel7.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(125, 125, 125))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newcontact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletecontact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(management, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savedata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name)
                    .addComponent(account)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(position)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(management)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newcontact)
                    .addComponent(deletecontact)
                    .addComponent(savedata))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcontactActionPerformed
        //Llamo al texto de forma legible y con trim() elimino espacios en blanco  
        String namestr = name.getText().trim();
        String accountstr = account.getText().trim();
        String positionstr = position.getText().trim();
        String managementstr = management.getText().trim();
        String phonestr = phone.getText().trim();
        String locationstr = location.getText().trim();
        
        // Condicional que verifica que obligatoriamente se deben ingresar los datos minimos para realizar el registro
        if (namestr.isEmpty() || accountstr.isEmpty() || phonestr.isEmpty() ||locationstr.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, complete obligatotiamente Nombre, Correo, Telefono y Ubicación.",
                "Campos Incompletos",
                JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución del método aquí
    }
        
        //Hago uso del contructor en la clase User
        User users = new User(namestr,accountstr,positionstr,managementstr,phonestr,locationstr );
        
        //Crea un mensaje de confirmación de datos
        String message = "¿Son correctos los siguientes datos?\n\n" +
                                 "Nombre Completo: " + users.getName() + "\n" +
                                 "Correo Corporativo: " + users.getAccount() + "\n" +
                                 "Cargo: " + users.getPosition() + "\n" +
                                 "Gerencia " + users.getManagement() + "\n" +
                                 "Telefono: " + users.getPhone() +"\n" +
                                 "Ubicación: " + users.getLocation();
        
        //se crea con joptionpane una ventana de confirmación aparte
        int respuesta = JOptionPane.showConfirmDialog(this, // "this" es la ventana actual
            message,
            "Confirmar Registro",
            JOptionPane.YES_NO_OPTION, // Botones de "Sí" y "No"
            JOptionPane.INFORMATION_MESSAGE); // Icono de información
        
        
        //Condicional donde confirmamos que el usuario haya marcado Yes para poder continuar 
        if (respuesta == JOptionPane.YES_OPTION){
            //Agrego el objecto a la lista
            listusers.add(users);
        
             //Filas para la tabla, parte visual
             o[0] = users.getName();
             o[1] = users.getAccount();
             o[2] = users.getPosition();
             o[3] = users.getManagement();
             o[4] = users.getPhone();
             o[5] = users.getLocation();
        
            //Agrego las filas (o) a la tabla, parte visual
            dtm.addRow(o);
        
            //Una vez agregado los datos, estos se limpian, para agregar otros
            name.setText("");
            account.setText("");
            position.setText("");
            management.setText("");
            phone.setText("");
            location.setText("");
            
            //Mensaje final donde confirmamos que el usuario se registro correctamente
            JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.");
         
        }
             
    }//GEN-LAST:event_newcontactActionPerformed

    private void deletecontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecontactActionPerformed
       // El sistema dependiendo de donde se ponga el cursor detecta que columna o numero es
        int listselect = Table.getSelectedRow();

        // Solo continúa si listselect es 0 
        if (listselect >= 0) {
        
        // Usamos el índice de la tabla (listselect) para tomar el User de tu ArrayList
        User userParaBorrar = listusers.get(listselect);

        //Mensaje para confirmar la eliminacion del registro
        String message = "¿Está seguro de que desea eliminar este registro?\n\n" +
                         "Nombre Completo: " + userParaBorrar.getName() + "\n" +
                         "Correo Corporativo: " + userParaBorrar.getAccount() + "\n" +
                         "Cargo: " + userParaBorrar.getPosition() + "\n" +
                         "Gerencia: " + userParaBorrar.getManagement() + "\n" +
                         "Telefono: " + userParaBorrar.getPhone() + "\n" +
                         "Ubicación: " + userParaBorrar.getLocation();

           int respuesta = JOptionPane.showConfirmDialog(this,
            message,
            "Confirmar Eliminación", // Título más apropiado
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE); // Icono de advertencia es mejor para borrar

        // Solo si el usuario presiona "Sí"...
        if (respuesta == JOptionPane.YES_OPTION) {
            
            // ...procede a borrar de la lista y de la tabla.
            listusers.remove(listselect);
            dtm.removeRow(listselect);
            
           //Mensaje confirmando la eliminación del registro 
           JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente.");
        }
        
        } else {
        //Notifica al usuario si no se ha seleccionado un registro para poder eliminarlo
        JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione un registro de la tabla para eliminar.", 
                "Ningún registro seleccionado", 
                JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_deletecontactActionPerformed

    private void savedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedataActionPerformed
        // 1. Verificar si hay algo que guardar
        if (listusers.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
            "No hay registros nuevos para guardar.", 
            "Lista Vacía", 
            JOptionPane.INFORMATION_MESSAGE);
            return; // detiene el proceso
    }
        //
        String sql = "INSERT INTO users (name, account, position, management, phone, location) " +
                 "VALUES (?, ?, ?, ?, ?, ?)";
        
        //Crear instancia de la base de datos
        Postgress_database database = new Postgress_database();
        
        // 3. Usar "try-with-resources" para asegurar que la conexión se cierre
       try (Connection conn = database.conectar();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        // 4. Recorrer tu ArrayList de usuarios
        for (User user : listusers) {
            // 5. Asignar los valores a los "?" del SQL
            pstmt.setString(1, user.getName());
            pstmt.setString(2, user.getAccount());
            pstmt.setString(3, user.getPosition());
            pstmt.setString(4, user.getManagement());
            pstmt.setString(5, user.getPhone());
            pstmt.setString(6, user.getLocation());

            // 6. Añadir la consulta al lote (en lugar de ejecutarla 1 por 1)
            pstmt.addBatch();
        }

        // 7. Ejecutar todas las consultas del lote de una sola vez
        int[] resultados = pstmt.executeBatch();

        // 8. Confirmar la transacción
        conn.commit();

        // 9. Informar al usuario y limpiar
        JOptionPane.showMessageDialog(this, 
                "¡Se guardaron " + resultados.length + " registros exitosamente en la base de datos!", 
                "Guardado Exitoso", 
                JOptionPane.INFORMATION_MESSAGE);

        // 10. Limpiar la lista y la tabla para evitar guardar duplicados
        listusers.clear();       // Vacía la lista en memoria
        dtm.setRowCount(0);      // Borra todas las filas de la tabla visual

    } catch (SQLException e) {
        // 11. Manejar cualquier error de SQL
        JOptionPane.showMessageDialog(this, 
                "Error al guardar en la base de datos:\n" + e.getMessage(), 
                "Error SQL", 
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_savedataActionPerformed

    private void managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managementActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField account;
    private javax.swing.JButton deletecontact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField management;
    private javax.swing.JTextField name;
    private javax.swing.JButton newcontact;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField position;
    private javax.swing.JButton savedata;
    // End of variables declaration//GEN-END:variables
}
