/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cun.edu.co.main.designer;

import cun.edu.co.main.Postgress_database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import cun.edu.co.main.designer.ViewTickets;

/**
 *
 * @author thor
 */
public class Tickets extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tickets.class.getName());

    /**
     * Creates new form Tickets
     */
    public Tickets() {
        initComponents();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JComboBox<>();
        equiphment = new javax.swing.JTextField();
        support = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        manageusers = new javax.swing.JButton();
        viewdata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        equiphment.setBackground(new java.awt.Color(0, 0, 0));
        equiphment.setForeground(new java.awt.Color(255, 255, 255));

        support.setBackground(new java.awt.Color(0, 0, 0));
        support.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel2.setText("Equipo Asignado");

        jLabel3.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de Soporte");

        jLabel4.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jLabel4.setText("Descripción de la Falla");

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setColumns(20);
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setRows(5);
        jScrollPane1.setViewportView(report);

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Create Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageusers.setBackground(new java.awt.Color(153, 0, 0));
        manageusers.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        manageusers.setForeground(new java.awt.Color(0, 0, 0));
        manageusers.setText("Manager User");
        manageusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersActionPerformed(evt);
            }
        });

        viewdata.setBackground(new java.awt.Color(0, 204, 255));
        viewdata.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        viewdata.setForeground(new java.awt.Color(0, 0, 0));
        viewdata.setText("View Data");
        viewdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(support, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equiphment, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageusers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewdata)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equiphment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(support, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(manageusers)
                            .addComponent(viewdata))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersActionPerformed
        Showpanel panelUsuarios = new Showpanel();
        panelUsuarios.setVisible(true);
        panelUsuarios.setLocationRelativeTo(this);
    }//GEN-LAST:event_manageusersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userstr = (String) user.getSelectedItem();
        String equiphmentstr = equiphment.getText().trim();
        String supportstr = support.getText().trim();
        String reportstr = report.getText().trim();
        
        // 2. Validar que los campos no estén vacíos
         if (equiphmentstr.isEmpty() | supportstr.isEmpty() || reportstr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

        // 3. Preparar el SQL
        // Esta consulta COINCIDE con la estructura de tu tabla
        String sql = "INSERT INTO tickets (user_report, equiphment_assigned, type_support, report, state) " +
                     "VALUES (?, ?, ?, ?, ?)";
    
         Postgress_database database = new Postgress_database();

        // 4. Usar try-with-resources para la conexión
          try (Connection conn = database.conectar();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

        // 5. Asignar los valores a los "?"
        pstmt.setString(1, userstr);
        pstmt.setString(2, equiphmentstr);
        pstmt.setString(3, supportstr);
        pstmt.setString(4, reportstr);
        pstmt.setString(5, "Abierto"); // Ponemos un estado por defecto

        // 6. Ejecutar el guardado
        pstmt.executeUpdate();

        // 7. Informar al usuario y limpiar los campos
        JOptionPane.showMessageDialog(this, "Ticket creado exitosamente.");
        
        equiphment.setText("");
        support.setText("");
        report.setText("");
        user.setSelectedIndex(0); // Volver al primer usuario

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el ticket: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdataActionPerformed
        ViewTickets vista = new ViewTickets();
        vista.setVisible(true);
        vista.setLocationRelativeTo(this);
 
    }//GEN-LAST:event_viewdataActionPerformed
    
    private void cargarUsuarios(){
    String sql = "SELECT account FROM users ORDER BY name ASC";
    Postgress_database database = new Postgress_database();

    try (Connection conn = database.conectar();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        // Limpiamos el ComboBox por si acaso
        user.removeAllItems(); 

        // Agregamos cada "account" de la BD al ComboBox
        while (rs.next()) {
            user.addItem(rs.getString("account"));
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar la lista de usuarios: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField equiphment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageusers;
    private javax.swing.JTextArea report;
    private javax.swing.JTextField support;
    private javax.swing.JComboBox<String> user;
    private javax.swing.JButton viewdata;
    // End of variables declaration//GEN-END:variables
}
